# Generated by Django 5.1.4 on 2025-08-06 02:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MundiMapProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('mundi_project_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MundiLayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('layer_type', models.CharField(choices=[('vector', 'Vector'), ('raster', 'Raster'), ('point_cloud', 'Point Cloud')], max_length=20)),
                ('mundi_layer_id', models.CharField(max_length=255, unique=True)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='mundi_layers/')),
                ('style_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('map_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='mundi_gis.mundimapproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MundiMapRender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('render_id', models.CharField(max_length=255, unique=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='mundi_renders/')),
                ('width', models.IntegerField(default=800)),
                ('height', models.IntegerField(default=600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('map_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renders', to='mundi_gis.mundimapproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
